name: ci
on: pull_request
jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run linters
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest
          args: --timeout=3m
  go-test:
    strategy:
      matrix:
        go-version: [1.22.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: go tests
        run: (set -o pipefail && go test -v -covermode=count -json ./... | tee test.json)
      - name: annotate go tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.5.1
        with:
          test-results: test.json

  test:
    runs-on: ubuntu-latest
    # Define any services needed for the test suite (or delete this section)
    # services:
    #   postgres:
    #     image: postgres:16
    #     ports:
    #       - "5432:5432"
    #     env:
    #       POSTGRES_PASSWORD: secretpassword
    env:
      BATON_LOG_LEVEL: debug
      # Add any environment variables needed to run baton-victorops
      # BATON_BASE_URL: 'http://localhost:8080'
      # BATON_ACCESS_TOKEN: 'secret_token'
      # The following parameters are passed to grant/revoke commands
      # Change these to the correct IDs for your test data
      CONNECTOR_GRANT: 'grant:entitlement:group:1234:member:user:9876'
      CONNECTOR_ENTITLEMENT: 'entitlement:group:1234:member'
      CONNECTOR_PRINCIPAL: 'user:9876'
      CONNECTOR_PRINCIPAL_TYPE: 'user'
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - name: Checkout code
        uses: actions/checkout@v4
      # Install any dependencies here (or delete this)
      # - name: Install postgres client
      #   run: sudo apt install postgresql-client
      # Run any fixture setup here (or delete this)
      # - name: Import sql into postgres
      #   run: psql -h localhost --user postgres -f environment.sql
      #   env:
      #     PGPASSWORD: secretpassword
      - name: Build baton-victorops
        run: go build ./cmd/baton-victorops